### ISSUE TITLE
No module named 'demofusion.watermark'

### ISSUE THREAD

**Issue by thejohnd0e** [sebaxakerhtc/sd-webui-demofusion#16]
![Screenshot - 2024-04-14 12 11 39](https://github.com/sebaxakerhtc/sd-webui-demofusion/assets/115493464/89e30c35-30fc-44e1-ac4f-03c1d7b624dc)

**Comment by sebaxakerhtc** [comment]
@thejohnd0e 
Hi and thank you for the issue.
Try it now - does it work for you after changes?

Upd. Screenshot is not about this extension

**Comment by thejohnd0e** [comment]
> @thejohnd0e Hi and thank you for the issue. Try it now - does it work for you after changes?
> 
> Upd. Screenshot is not about this extension

sorry, my fault!)
this is correct screenshot

![Screenshot - 2024-04-14 13 42 56](https://github.com/sebaxakerhtc/sd-webui-demofusion/assets/115493464/8c7c358f-64fc-4717-8a6b-c7fe87cdb173)

**Comment by sebaxakerhtc** [comment]
I made the changes. Did you tried it?

**Comment by thejohnd0e** [comment]
Yes, but when I try to use SDXL as the base model, I get some errors.


![Screenshot - 2024-04-14 20 54 13](https://github.com/sebaxakerhtc/sd-webui-demofusion/assets/115493464/6198e88e-34cd-4411-947a-95ef6b18f393)

**Comment by sebaxakerhtc** [comment]
looks likebyou choosed sd1.5 checkpoint inside the Demofusion  tab.


вс, 14 апр. 2024 г., 21:04 thejohnd0e ***@***.***>:

**Comment by thejohnd0e** [comment]
yes, i did) thank you!
